### PR TITLE
Support parsing mvnvm and SDKMAN! configuration files

### PR DESCRIPTION
**Pull request by Andrew-Dunn**
Adds basic support for parsing both mvnvm.properties files from [mvnvm](https://bitbucket.org/mjensen/mvnvm/src/master/), and .sdkmanrc files from [SDKMAN!](https://sdkman.io).

### Big change

⚠️ Assumes **mise-plugins/asdf-maven** will be renamed to **mise-plugins/mise-maven** ⚠️

### Current limitations
Only supports parsing maven version information, other settings such as `mvn_opts` or `user_uri` are not currently supported.

### Other additions
Added unit tests for new functionality, and moved project license to Apache 2.0 for better compatibility with patent
licensing clauses of Apache-licensed bundled dependencies.

#### Automated

Added automated regression tests (and GitHub Actions) that check:

- Mvnvm config files can be parsed correctly
  - Standard
  - Whitespacey
  - Heavy comments
  - Config file without a `mvn_version` property is ignored without erroring
- SDKMAN! config files can be parsed correctly
  - Extracting version name from file with comments, and other tools specified
  - Config file without a `maven` property is ignored without erroring
- `list-legacy-filenames` returns both `.sdkmanrc` and `mvnvm.properties`.

#### Manual

- Tested that mise picks up the version of maven requested by each test case.
- Tested that existing functionality still works

Screenshot 2024-04-28 at 8 59 35 pm

### CODE REVIEW

**Comment by jdx** [comment]
Nice work! Might take me a while to have time to go through it. Also going to tag @roele as our chief Java scientist on the team in case he has any thoughts but the description sounds straightforward.

**Comment by RandyTheAtlassian** [comment]
> Nice work! Might take me a while to have time to go through it. Also going to tag @roele as our chief Java scientist on the team in case he has any thoughts but the description sounds straightforward.

Thanks, if either of you would like to sync in Discord, just tag me and we'll find a time.

**Review by roele — APPROVED** [review]

**Comment by roele** [comment]
Great work indeed 👍

**Comment by Andrew-Dunn** [comment]
If it makes it easier, I can revert the changes to bin/install, and bin/latest-stable and bin/list-all (all shfmt changes) to simplify the PR?

**Pull request merged**
